# Results will be saved to neosr/experiments/results/

name = "test_8x"
model_type = "image"
scale = 8
#use_amp = true
#compile = true

[datasets.test_8x]
name = "test"
type = "single"
dataroot_lq = 'D:/py/towl/fs/UKBiobankDataset/test/8x/Conf_65'

[val]
tile = -1

[network_g]
#type = "hat_s"
type = "hat_m"
#type = "hat_l"

[path]
pretrain_network_g = 'D:/py/towl/neosr/experiments/train_8x/models/net_g_20000.pth'